### ISSUE TITLE
request permission to upload to curseforge

### ISSUE THREAD

**Issue by cpjet64** [Vicious-wow/XIV_Databar#10]
as titled. I have uploaded another addon from another author with their permission and all due credit just looking to push this as well.

**Comment by Vicious-wow** [comment]
What for?

**Comment by cpjet64** [comment]
availability to some friends who only know how to use the twitch client for addons.

**Comment by Vicious-wow** [comment]
Hm, fair enough. I was thinking about putting this thing up on curse eventually anyway, just felt like it's not in good enough state yet.
Hoping it doesn't piss you off, just letting you know that I'll upload this to curse in the near future after i've made a few more changes. 2 weeks max.

**Comment by Revanbane** [comment]
@cpjet64 
And would you steal just this version or all the updates as well? Are you forwarding the authors all the earnings from the addon downloads, however much they may be? What happens when someone has a bug report or a feature request, or when the client messes up the install? Do you even know who else contributed to this addon and needs to be credited as well?

Stay out of other people's work.

**Comment by cpjet64** [comment]
@Revanbane I'm not sure why you're being so hostile but this is how I have done it in the past. https://www.curseforge.com/wow/addons/adibags-keystones 
I don't get any earnings at all from it and all bug reports and feature requests get pushed directly to the author's Github.
It's also not hard looking through all the past credits and making sure everyone who has worked on it in the past gets the correct credit.
Also please never refer to a request to post someone else's work as outright theft. That is a quick way to get a defamation lawsuit and don't think for a second that because you're online you can't be found and sued. I did the proper thing by asking for permission from the latest author being doing anything even though the license allows for it.
@Vicious-wow Thank you and no worries it doesn't upset me at all! I will just have to continue manually installing it for my friends with teamviewer.

**Comment by Revanbane** [comment]
I'm one of the people currently contributing to this project so I'm directly involved. And what you are suggesting doing equals to theft of someone else's work however you sugarcoat it. You might be able to do it without consequence but it doesn't mean it isn't scummy in every way. Do not take other people's work is something that is vividly clear to any creator of content. Usually the simple basic respect is enough to never even make such requests in the first place.

The project is still actively being worked on, respect that.

Btw I'd love for you to take a claim of defamation to any lawyer, they'd laugh you out of their office. Especially since now you're threatening to doxx me, which may in fact be illegal wherever you're from and is illegal where I'm from.

**Comment by Vicious-wow** [comment]
There's no reason to get upset this much.
I just generally don't trust strangers on the internet, especially when there's money involved. Curse pays out a share of their ad revenue to addon creators depending on their addon's success, so someone uploading an addon as the middle man is way more complicated than you (@cpjet64 ) might think. And I couldn't trust you to actually paypal me the revenue or update curse's version quick enough after it's been updated here, no offense.
And to clarify: even though someone could download this entire github and upload it to curse or wherever else and be _technically_ within legal rights to do so, I would simply delete this repository and keep the addon updated for myself only. So if anyone wanted to do that, they'd only be screwing themselves and everyone else who uses this addon over, so i'm not really concerned about that.

**Comment by cpjet64** [comment]
@Vicious-wow I have no issues with you at all and I appreciate and understand where you're coming from as I am also a developer. I can and will totally respect that.
The only issue that has arisen is from Revanbane who is claiming to be an author when they are not linked/cited anywhere at all. They have no commits, additions, deletions, etc. I also wish they would learn the definition of doxing considering finding someone's info and suing them for defamation is not what they claim. Too many people like Revan have gotten comfortable hiding behind their keyboards. 
Regardless they have already violated Githubs community guidelines and I have reported them.
Any further comments from Revanbane will just cement his/her harassment that I have already contacted Github staff about.

Vicious, I wish you the best of luck! I cant wait to see your finished product!

**Comment by Vicious-wow** [comment]
Revan said: 
> I'm one of the people currently contributing to this project so I'm directly involved.
Never was there a mention of claiming to be an author. Revan has helped me with certain parts of the code as well as pretty much anything graphical / design-y that were changed in the addon. Add to that coming up with ideas and concepts for functionality. Not showing up as a contributor in github does not mean there were no contributions, when he changes or creates something he simply sends it to me and i test it out and then update the github with it. Plus the changed code before this was even uploaded on github.

And let's get back to reality. You've made a request (which I honestly think was rude). Revan has had his work stolen in the past, so I can't really fault anyone who's had negative experiences with this to also get upset at your request. I've never had anything of the sort happen to me before so I guess I'm calmer than I should be about it. The reason why I think your request was rude, is because you're not asking me if I will be uploading this to curse, and if so when. You went straight to asking to upload it yourself without mentioning how uploads (when you're not playing the game anymore) will be handled, or how addon revenue will be handled (which since you're a developer you know exists). I think it's completely understandable for someone who's had bad experiences with this to think you're trying to do something shady here. Even I thought it was kind of shady and my first reaction was "hey maybe I should let him deal with curse" - before I started thinking about it.
To then threaten with a defamation lawsuit because a stranger on the internet said something you didn't like is not only ridiculous but also completely escalating the issue. Your intense reaction to "theft" with your already rude initial request and flimsy reason as to why you want to upload it to curse makes me think even worse of this. 

I won't tolerate any more comments against contributors. In case you truly weren't trying to do something shady and only meant good by this, I'm sure you can see how I've come to my conclusions.

**Comment by Revanbane** [comment]
It makes me incredibly happy you value both of our work (because yes, I am contributing to this project) enough to stoop to base threats, all of which I reject. Since you've forced me to defend myself I have had to contact GitHub support myself and make them waste their time dealing with this mess. 

My only hope is you learn to respect other people's work in the future.
