### ISSUE TITLE
Question: Reposition Icons

### ISSUE THREAD

**Issue by lightsourced** [Vicious-wow/XIV_Databar#14]
Hiya! Not really an issue, but I wasn't sure where to ask this. Is there a way to move the different icons/modules around? If not, could this maybe be added? Perhaps you could make it so that you can hold shift and left click drag them around the bar? I think titan bar did it like this and then the icons would snap to either left right middle etc. Also, the ability to add padding and such. I guess just more visual customization options would be super welcome!

**Comment by Vicious-wow** [comment]
Heya. I remember seeing this feature request in the previous author's github issue tracker and have thought about it a lot. To be brutally honest with you, the way the code is written to determine where each module is supposed to be is written in a really bad way. To be able to add this would require to rewrite a LOT of code. Instead of handling the position of each module within each module I'd have to create a module specifically to handle positioning for every other module which makes adding this very complex given with how the addon is written.
I know this isn't good news for you and everyone who wants this feature added to the addon. I've honestly played with the idea of writing an entire databar addon from the ground up just so I don't have to deal with the many instances of badly written code that is difficult to change. For now I'm basically just lazy and playing the game, but until shadowlands i at least want to finish my to-do list and put this thing on curseforge. After that, with nothing else in mind and no bugs to fix I might either start writing a new databar addon from scratch with the looks of XIV Databar, or scramble up a solution for users to position modules themselves.
