### ISSUE TITLE
Bug and Feature Request

### ISSUE THREAD

**Issue by TheCynicalKitty** [Vicious-wow/XIV_Databar#17]
Ok, so I set up my bar and copied it to "Default", I went to another char and set the default as the profile, but the setting "Use Class Color" is using the color of the previous class it was set to, it's not adapting to the new class color.

Feature: Use default profile by default, it seems to be making a new profile by default instead and is kind of irritating to constantly reposition the bar and fix the settings.

Great plugin though super digging it, any plans to add this to curse for ease of access updating :)

**Comment by TheCynicalKitty** [comment]
Basically, I wanted one universal profile "default" that I could use across all my char's this is currently my UI setup of my paladin 
https://thecynicalkitty.com/s/20200616454.jpg

would love it if I could set up "default" as a profile with all the settings I wanted to use and adaptive class color settings so it blends in nicely cross all my char's

**Comment by Vicious-wow** [comment]
Heya.
Which settings are not getting saved when using the Default profile on another char? At first it seems like only the "use class color" setting, but then you say "reposition the bar and fix the settings", so i'm guessing more things aren't actually saved? Or nothing at all and it just goes to complete default on every char again?
For info on a curse release, check the github's readme.

**Comment by TheCynicalKitty** [comment]
Do you have discord id love to screen share whats happening :) with you so you can see in detail what I mean.

**Comment by Vicious-wow** [comment]
Send me your tag.

**Comment by TheCynicalKitty** [comment]
TheCynicalKitty | Chris#8113

Copy all of that :)

**Comment by Vicious-wow** [comment]
To summarise:

- Regular Font color for icons/text on the bar does not get updated between chars when "use class colors" is selected
- New chars should default to the Default profile instead of making a profile for themselves with default settings
- Add an option to load a specific profile on all characters
- Rename armor module text because it's confusing as fuck
- Add coordinates to the very right of the micromenu as a quick fix because making a module for it is too much work with how the addon handles module positioning

**Comment by Vicious-wow** [comment]
Normal text color actually uses class color now (changing between classes on the same profile as intended), new chars will default to the Default profile. The armor module now lets you show coordinates to the right of the ilvl text (if enabled). Updated confusing descriptions in the armor module options.
I've tried to use a resource-friendly approach towards the coordinates module, but you're essentially doing multiple API calls every 0.1s to update the coordinates. It's resource intensive and quickly fills your RAM until lua decides it's time to garbage collect. I'm avoiding the go-to API call to get player coords because it keeps creating a new table everytime it's called, stacking up your system tray quickly.
Report any bugs that may or may not occur now. If there's nothing by tomorrow evening I'll close the thread myself.
