### ISSUE TITLE
Currency tooltip displays amount as 0/0

### ISSUE THREAD

**Issue by wuhan890809** [Vicious-wow/XIV_Databar#20]
Hi, sorry to bother you again.
The currency tooltip always displays the amount of currencies as 0/0
I think that maybe because in line 292 of currency.lua the two variables`quantity` and `maxQuantity`
should be `curInfo.quantity` and `curInfo.maxQuantity`?

**Comment by Vicious-wow** [comment]
Hey again. Looking at the code you're probably (hopefully) right. I remember changing quantity and maxQuantity to curInfo.quantity etc. because the way the module retrieved information about currency happened via a deprecated API call which caused the thing to crash. I must've missed updating those 2 in the process.
Might I ask what the chinese signs for "Classic" are in the last issue thread we discussed? You said you localized it but you didn't say what the signs are. I'd like to add that to this github version so other chinese players don't have their addon blow up. What did you end up using for the dummy value? Would be nice if you can hit me up with the proper chinese signs that say something along the lines of "Failed to retrieve info" or something else that makes sense  there.

**Comment by wuhan890809** [comment]
Thank you for replying.
The world "Classic" is translated as "经典怀旧服" in Simplified Chinese WoW client(And only, Tranditional Chinese use other words that I'm not quite sure about). So I simply added `L["Classic"] = "经典怀旧服"` at the end of zhCN locale file. I have to say it's annoying that Blizzard doesn't make it a global string, so you have to maintain different phrases for different languages.
As for the dummy value, I'm sorry I didn't use one.Because I just made variable `charNameFormat` return `"(|c|cffecd672" .. richPresence .. "|r)"` to bypass that wierd situation with an `if charName == nil then` clause. Obviously that's not a good way.
The Chinese phrase for "Failed to retrieve info" is "信息获取失败". May it be of some help.

**Comment by Vicious-wow** [comment]
Thanks for providing this information. I've altered the locale files and micromenu to account for alliance/horde, "classic" and charNames being nil.
