### ISSUE TITLE
Addition of other Hearthstones

### ISSUE THREAD

**Issue by Caluril** [Vicious-wow/XIV_Databar#38]
Would it be possible to add the rest of the Hearthstone toys?

`    172179, -- Eternal Traveler's Hearthstone
    168907, -- Holographic Digitalization Hearthstone
    163045, -- Headless Horseman's Hearthstone
    162973, -- Greatfather Winter's Hearthstone
    166746, -- Fire Eater's Hearthstone
    166747, -- Brewfest Reveler's Hearthstone
    165670, -- Peddlefeet's Lovely Hearthstone
    165802, -- Noble Gardener's Hearthstone
    165669, -- Lunar Elder's Hearthstone
    142298, -- Astonishingly Scarlet Slippers
    184353, -- Kyrian Hearthstone
    183716, -- Venthyr Sinstone
    182773, -- Necrolord Hearthstone
    180290, -- Night Fae Hearthstone`

**Comment by Vicious-wow** [comment]
Will implement this whenever I have time today. Not really playing anymore, so if any bugs occur you'll have to let me know so I can fix them.

**Comment by Caluril** [comment]
After thinking about the heart toys, perhaps it would be better to add them in to the Port options?

I can be be a bit busy too, I understand. I hope you and your family are safe and well.

Shout out if you need help, I'll do my best to assist

**Comment by Vicious-wow** [comment]
I haven't really been busy, just kind of forgot about it and couldn't be bothered. Sorry, just haven't been feeling like doing much on the addon lately. No promises, but will _probably maybe actually_ look at it today.

**Comment by Vicious-wow** [comment]
Alright, I added the ones you linked, double checked IDs and looked for any toy that might be missing still. Couldn't find anything amiss, but that doesn't guarantee something won't break. Download the updated "travel.lua" file in modules on this github, throw it in your folder and let me know if it works.

**Comment by ghost** [comment]
Okay, I'll check it out now

For Wrap of Unity, would be nice to add that in the Port Options, though it doesn't automatically equip, but I have the habit of equipping before clicking the link in the bar any way, thought it would be nice without using any macro's or action bar's etc.

`if IsUsableItem(63206) and not self.portOptions[63206] then
    self.portOptions[63206] = {portId = 63206, text = GetItemInfo(63206)} -- wrap of unity (alliance)
  end`
 ` if IsUsableItem(63207) and not self.portOptions[63207] then
    self.portOptions[63207] = {portId = 63207, text = GetItemInfo(63207)} -- wrap of unity (horde)
  end`

-update-
I tested the Hearthstones and they work, though since I have both the Eternal Traveler's Hearthstone and Night Fae Hearthstone and they both share the same actions while using them, so it hard to tell which is used but, hey, it works.
I know that the default hearthstone will be used if it's in the inventory ;)

I am a guide writer for DugiGuides :)
I admire your work by updating this awesome databar for Shadowlands. Keep up with this awesome work and stay safe.

**Comment by Vicious-wow** [comment]
There's a LOT more items that require to be equipped and allow you to port somewhere. The list is as big as the regular hearthstone list in the travel module right now, or longer. 
It should be possible to set an item like that as a port option by clicking on it to equip, then clicking again when it's activateable. The process to do this would require a proper rework of the travel module which I really don't feel like doing, especially when not playing the game anymore. The way CD of hearthstones and port options is handled has always annoyed me, and I feel there should be a real timer, or at least fill out the text of the hearthstone more and more as the cooldown becomes less.
Adding the equippable ports is something that's both too niche and not really asked for, apart from you, as well as a rework of the travel module to properly display cooldowns and equip port options.
